config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home', to: 'home#index'
  root to: 'home#index'
  resources :websites
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :websites
end

app/models/website.rb
class Website < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  def index
    @websites = current_user.websites
  end

  def new
    @website = Website.new
  end

  def create
    @website = current_user.websites.create(website_params)

    if @website.save
      redirect_to @website
    else
      render 'new'
    end
  end

  def show
    @website = Website.find(params[:id])
  end

  def edit
    @website = Website.find(params[:id])
  end

  def update
    @website = Website.find(params[:id])

    if @website.update(website_params)
      redirect_to @website
    else
      render 'edit'
    end
  end

  def destroy
    @website = Website.find(params[:id])
    @website.destroy
    redirect_to websites_path
  end

  private
    def website_params
      params.require(:website).permit(:title, :contact_us, :beliefs)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/home/index.html.erb
Home Page<br>
<% if current_user %>
  <%= link_to(image_tag('blue-on-light'), 'http://stripe.com') %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CornerstoneGiving</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%= notice %></p>
    <p><%= alert %></p>
    <p>
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
      <% else %>
        <%= link_to('Login', new_user_session_path)  %>
      <% end %>
    </p>
    <%= yield %>
  </body>
</html>

app/views/websites/edit.html.erb
<h1>Editing website</h1>
<%= form_for @website, method: :patch do |website| %>
  <% if @website.errors.any? %>
    <ul>
      <% @website.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <p>
    <%= website.label :title %><br>
    <%= website.text_field :title %>
  </p>
  <p>
    <%= website.label :contact_us %><br>
    <%= website.check_box :contact_us %>
  </p>
  <p>
    <%= website.label :beliefs %><br>
    <%= website.check_box :beliefs %>
  </p>
  <p>
    <%= website.submit %>
  </p>
<% end %>
<%= link_to 'Back', websites_path %> <%= link_to 'Cancel', website_path(@website) %> <%= link_to 'Delete', website_path(@website), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/websites/index.html.erb
<h1>Websites</h1>
<%= link_to 'New Website', new_website_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Contact Us</th>
    <th>Beliefs</th>
  <tr>
  <% @websites.each do |website| %>
    <tr>
      <td><%= website.title %></td>
      <td><%= website.contact_us %></td>
      <td><%= website.beliefs %></td>
      <td><%= link_to 'Show', website_path(website) %></td>
      <td><%= link_to 'Edit', edit_website_path(website) %></td>
      <td><%= link_to 'Delete', website_path(website), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/websites/new.html.erb
<h1>New Website</h1>
<%= form_for :website, url: websites_path do |website| %>
  <% if @website.errors.any? %>
    <ul>
      <% @website.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <p>
    <%= website.label :title %><br>
    <%= website.text_field :title %>
  </p>
  <p>
    <%= website.label :contact_us %><br>
    <%= website.check_box :contact_us %>
  </p>
  <p>
    <%= website.label :beliefs %><br>
    <%= website.check_box :beliefs %>
  </p>
  <p>
    <%= website.submit %>
  </p>
<% end %>
<%= link_to 'Back', websites_path %>

app/views/websites/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @website.title %>
</p>
<p>
  <strong>Contact Us:</strong>
  <%= @website.contact_us %>
</p>
<p>
  <strong>Beliefs:</strong>
  <%= @website.beliefs %>
</p>
<%= link_to 'Back', websites_path %> <%= link_to 'Edit', edit_website_path %> <%= link_to 'Delete', website_path(@website), method: :delete, data: { confirm: 'Are you sure?' } %>